FROM node:22-alpine AS base
WORKDIR /app
RUN npm install -g turbo

FROM base AS builder
COPY package.json turbo.json ./
COPY packages/notifyx-shared ./packages/notifyx-shared
COPY apps/notifyx-auth-service ./apps/notifyx-auth-service
RUN turbo run build --filter=notifyx-auth-service
RUN npm prune --omit=dev --workspace=notifyx-auth-service

FROM node:22-alpine AS runner
WORKDIR /app
COPY --from=builder /app .
USER node
EXPOSE 3001
CMD ["node", "apps/notifyx-auth-service/dist/index.js"]
