FROM node:22-alpine AS base
WORKDIR /app
RUN npm install -g turbo

FROM base AS builder
COPY package.json turbo.json ./
COPY packages/notifyx-shared ./packages/notifyx-shared
COPY apps/notifyx-admin-service ./apps/notifyx-admin-service
RUN turbo run build --filter=notifyx-admin-service
RUN npm prune --omit=dev --workspace=notifyx-admin-service

FROM node:22-alpine AS runner
WORKDIR /app
COPY --from=builder /app .
EXPOSE 3006
CMD ["node", "apps/notifyx-admin-service/dist/server.js"]
