FROM node:22-alpine AS base
WORKDIR /app
RUN npm install -g turbo

FROM base AS builder
COPY package.json turbo.json ./
COPY packages/notifyx-shared ./packages/notifyx-shared
COPY apps/notifyx-gateway ./apps/notifyx-gateway
RUN turbo run build --filter=notifyx-gateway
RUN npm prune --omit=dev --workspace=notifyx-gateway

FROM node:22-alpine AS runner
WORKDIR /app
COPY --from=builder /app .
EXPOSE 8080
CMD ["node", "apps/notifyx-gateway/dist/index.js"]
