FROM node:22-alpine AS base
WORKDIR /app
RUN npm install -g turbo

FROM base AS builder
COPY package.json turbo.json ./
COPY packages/notifyx-shared ./packages/notifyx-shared
COPY apps/notifyx-audit-service ./apps/notifyx-audit-service
RUN turbo run build --filter=notifyx-audit-service
RUN npm prune --omit=dev --workspace=notifyx-audit-service

FROM node:22-alpine AS runner
WORKDIR /app
COPY --from=builder /app .
USER node
EXPOSE 3005
CMD ["node", "apps/notifyx-audit-service/dist/server.js"]
